### ISSUE TITLE
Does not create executable for Mac OS 

### ISSUE THREAD

**Issue by krebznet** [FTEOTW/eclipse-rcp-tycho#1]
Do you know if its possible to create executable for Mac M1 chip ?

**Comment by FTEOTW** [comment]
Hi, this project only export for 64 windows version. 
You can try to modify the environment in the pom parent adding the corresponding tags. 
For example: 

`<environment>`
    `<os>macosx</os>`
    `<ws>cocoa</ws>`
    `<arch>x86_64</arch>`
`</environment>`

Regards
